# Generated by Django 5.0.7 on 2024-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img', models.ImageField(upload_to='images/')),
                ('book_name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('book_description', models.TextField(max_length=200, verbose_name='Description')),
                ('book_price', models.CharField(max_length=50, verbose_name='Price')),
                ('book_stock', models.CharField(max_length=50, verbose_name='Stock')),
            ],
        ),
    ]
